### ISSUE TITLE
Add instructions for setting up dev environment to README

### ISSUE THREAD

**Issue by benjamin-allen** [codidact/core#14]
Created from project card [here](https://github.com/codidact/core/projects/1#card-31614176)

The README needs instructions for setup for various operating systems. These instructions will certainly need maintenance as the project evolves.

I'll be performing a from-scratch install on a Windows PC without C# development tools and noting steps as I go.

**Comment by masonwheeler** [comment]
This process should be based around the same basic principle as [Joel Test point #2](https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/).  If we aren't able to go from zero to a working environment by executing a single script and letting it run unattended to completion, the script needs to be improved.

**Comment by ArtOfCode-** [comment]
Closed by #15.
