### ISSUE TITLE
Missing Migration execution at Runtime

### ISSUE THREAD

**Issue by misha130** [codidact/core#17]
As per https://github.com/codidact/core/pull/15/commits/c7dd9d8c53cc0c8fc724a9ac70e1ad284eb94c33 currently the execution of the migration is execute via a cli command.

Rather than that, this line of code should be added somewhere on start:
`dbContext.Database.Migrate()`

Exception handling for this should also be implemented since there is no proper connection string.

**Comment by benjamin-allen** [comment]
Would it be possible/desirable to check for a placeholder connection string and use in-memory database if it's present? The potential utility may be offset by the potential confusion ("why does everything reset when I restart the app?")

**Comment by misha130** [comment]
Short answer: I don't see any situation where a user would want to run an instance that is empty with no seed.

Long answer: 
At some point there was talk of choosing a database for this project and in this talk it was said that it doesn't really matter which database we choose and whoever wants to run an instance should be able to implement or configure his own database. 
On the matter of implementation of our interfaces so whoever runs the instance can do it on an excel for all I care - as of right now you can't because
a) migration which we create specifically for our db of choice 
b) specific features of the db that we use like bigserial and enums.
So on the matter of the configuration and to get back to your original question, we could add a configuration in the app settings like "dbType" and it might be sql, mysql or inmemory and then we will have to individually implement how each of them work. 
But again as per my short answer unless we are displaying a demo to someone using this in memory (which will require creating a seed and implementation) there really is little reason to do so.

Oh and having unexpected behavior like "connection string invalid -> switch to inmemory" is a good recipe for confusion

**Comment by benjamin-allen** [comment]
I played around with this idea and found a way to call the `Database.Migrate()` method in the `Startup.cs` `Configure` method.

The code is [here](https://github.com/benjamin-allen/core/blob/benjamin-allen/auto-migration/src/WebUI/Startup.cs#L59-L82) if you're interested.

**Comment by asynts** [comment]
~~I think an [`IStartupFilter`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.istartupfilter?view=aspnetcore-3.) is the intended way of doing it. Also `Configure` is called on every client request, if I understand that correctly, thus the call should be in `ConfigureServices` instead.~~ *(I thought `Configure` was called for each client request, I don't know where I got that idea from.)*

[This is what I am playing around with.][1]

*(Please note that I am not an experienced ASP.NET developer and just looked at the documentation.)*

  [1]: https://github.com/asynts/codidact-core/commits/asynts.playing-around-with-startup-filters

**Comment by misha130** [comment]
What @benjamin-allen wrote is more to the point. The only issue is I would prefer if Logger was used rather than exception data, like @asynts did in his code.

In general though, this issue is not high priority. I am not going to PR it right now or this/next week even. 
If you are ok with your code and think its good enough then PR it. The whole team will review and not just me.
