### ISSUE TITLE
How will this be different from other Q&A projects?

### ISSUE THREAD

**Issue by h6w** [codidact/core#2]
I ask because for the past few months I've been looking at [AskBot,](https://askbot.com/) which is used by [the LibreOffice Q&A site](https://ask.libreoffice.org/).

From [askbot.com](https://askbot.com/contribute/):

> Askbot is a free open source Question and Answer (Q&A) forum software written in Django and Python.

And also their [documentation](https://askbot.org/doc/index.html) starts with:

> Askbot is an open source Question and Answer (Q&A) forum project inspired by StackOverflow and YahooAnswers

Finally, [AskBot is licensed as GPL3](https://askbot.org/en/question/2709/which-kind-of-license-has-askbot/) and their [code is on GitHub](https://github.com/ASKBOT).

**Comment by manassehkatz** [comment]
@h6w Reasonable question. But our current plan is to use Github for actual development and for documentation once decisions have been made. The decision making, which has included some consideration of existing open source products, is primarily taking place in the Discord and the Forum - both have links on the codidact home page.

**Comment by ranolfi** [comment]
Safe to close this as the directions have been provided. :) Thanks for being interested and please join us in the forum discussions!

**Comment by nemobis** [comment]
Please don't reinvent the wheel! AskBot is perfectly fine and it's used by several large projects. Focus on building a community, not on redoing things from scratch.

**Comment by ArtOfCode-** [comment]
Please direct any conversation about this subject to [the forum](https://forum.codidact.org/).

cc @nemobis
