### ISSUE TITLE
SSL Labs: Implement HSTS, remove TLS 1.1?

### ISSUE THREAD

**Issue by mbomb007** [codidact/core#25]
The [SSL Labs result for Codidact](https://www.ssllabs.com/ssltest/analyze.html?d=forum.codidact.org&s=104.31.78.207&hideResults=on&latest) shows that TLS 1.1 ([deprecated](https://www.digicert.com/blog/depreciating-tls-1-0-and-1-1/)) is supported and that [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) is not.

The website "grade" given by SSL Labs (currently "A") will soon be capped at "B" due to support of TLS 1.1.

The website needs to support HSTS to get a grade of "A+".

**Comment by TheHelmar** [comment]
I consider TLS 1.1 to be dead enough, we should not support it.

**Comment by ArtOfCode-** [comment]
cc @bertiebaggio

**Comment by ranolfi** [comment]
Kill TLS 1.1, make it 1.2+.

I strongly oppose to enabling HSTS at this time; we've had problems with HTTPS misconfiguration in the forum software and I don't feel too confident these are not going to happen again sometime soon.

**Comment by ranolfi** [comment]
@ArtOfCode- , you're managing CloudFlare for both the forum and home page right? Feel free to drop TLS 1.1 (from SSL/TLS -> Edge Certificates -> Minimum TLS Version).

**Comment by ArtOfCode-** [comment]
Aye, can do - but this also needs bertieb to disable TLS 1.1 between CF and origin.

**Comment by bertiebaggio** [comment]
Done, only TLS 1.2 and 1.3 now. 

![codidactprotos](https://user-images.githubusercontent.com/7524620/72802842-9399e300-3c44-11ea-8426-6f31f9529b0a.jpg)
