### ISSUE TITLE
Add a C# linter and configure for Microsoft style guide

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/core#26]
We should have a linter in the project to make it easy for folks to automatically fix their code to the style guide.

Style guide here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

Whatever we choose, we'll need to configure it for those settings.

**Comment by asynts** [comment]
https://github.com/dotnet/format

Not sure if it follows our exact style guide, but we could just use whatever this tool spits out instead. I mean style guides are mostly for consistency and this would work on Windows and Linux.

**Comment by ranolfi** [comment]
See https://github.com/codidact/core/blob/ranolfi/skeleton/Solution/.editorconfig (not final; still pending increased severity for some rules).

**Comment by misha130** [comment]
Maybe just copy it off rosalyn for example?
https://github.com/dotnet/roslyn/blob/master/.editorconfig

Your editorconfig @ranolfi forbade using lambda without a body and methods without a body

**Comment by ranolfi** [comment]
> Maybe just copy it off rosalyn for example?

Bad idea IMO, see for instance: `[*.{cs,csx,vb,vbx}]`. But use as reference, definitely.

> Your editorconfig @ranolfi forbade using lambda without a body and methods without a body

Can you give an example in code for both?

**Comment by misha130** [comment]
> Can you give an example in code for both?
Lambda: https://github.com/codidact/core/blob/13171a1cbdf1122c819a6eda24f936fd02a6d766/src/WebUI/Startup.cs#L54
Method: 
https://github.com/codidact/core/blob/13171a1cbdf1122c819a6eda24f936fd02a6d766/src/WebUI/Program.cs#L14

**Comment by LionelBergen** [comment]
I can work on this.

**Comment by ranolfi** [comment]
Oh damn, I wrote a lengthy answer here @misha130, my browser crashed and I was hoping GitHub would save a draft but it's gone :(

I was going to say that is by-design but, on second thought, that's not entirely a good thing, so I'll be comparing options. Anyway, no harm in accepting official standard right now and replacing any specific rule (along with necessary refactoring, which I step forward to do myself) if we so desire in the next days.

**Comment by asynts** [comment]
@ArtOfCode- This issue can be closed.
