### ISSUE TITLE
Make it decentralized

### ISSUE THREAD

**Issue by ghost** [codidact/core#3]
Can we please use ActivityPub to make the software decentralized? _Why have "100" isolated servers (with redundant content) when we can have one network comprised of "100" federating instances (servers)._

**Comment by luap42** [comment]
This is also under discussion on our forum:

https://forum.codidact.org/t/decentralized-website/96

**Comment by Daksh14** [comment]
Closing as the directions have been provided. Don't forget to join us in with discussions!
