### ISSUE TITLE
Privacy policy page is empty

### ISSUE THREAD

**Issue by jflopezfernandez** [codidact/core#36]
The privacy policy page is currently empty. I'm currently working on populating the page with [the privacy policy from the forum](https://forum.codidact.org/privacy).

**Comment by ArtOfCode-** [comment]
Note to all contributors: See linked pull request #37. We'll need to write a custom policy when we're further along in development; please hold off on implementing this for now.

**Comment by asynts** [comment]
I think this could be closed, it will be quite some time until we add the privacy policy. Alternative this could be added to a milestone, e.g. "final sprint".

**Comment by luap42** [comment]
Closing this with three different status tags, because this has been declined (see the other PR), because we'll need more information on how Codidact will collect data (because we can't know yet), and the idea behind implementing this now is therefore invalid. :)
