### ISSUE TITLE
Registration Page Needed

### ISSUE THREAD

**Issue by jflopezfernandez** [codidact/core#38]
There is currently no registration page for the site. I am currently working on implementing it.

**Comment by LionelBergen** [comment]
@ArtOfCode- Sounds like this is no longer in progress and we are waiting for wire frames
https://github.com/codidact/core/pull/39#issuecomment-580927220

**Comment by luap42** [comment]
Agreed. Closing this for now.

**Comment by cellio** [comment]
I got here from the "done" category on the project, but it sounds like this was abandoned not done.
