### ISSUE TITLE
Add setup instructions for Arch Linux

### ISSUE THREAD

**Issue by mcalexster** [codidact/core#50]
Current setup instructions point to a Microsoft download of dotnet core for various flavours of linux, which doesn't include Arch Linux.  Luckily, packages exist and can be installed by the Arch package manager, pacman

Instructions should be updated to include steps to install on Arch Linux

I have added instructions to readme.md.  PR coming.

**Comment by mcalexster** [comment]
Dealt with by @asynts.

**Comment by asynts** [comment]
https://github.com/codidact/core/pull/31#issuecomment-581050907
