### ISSUE TITLE
Outdated .NETStandard ?

### ISSUE THREAD

**Issue by appgurueu** [codidact/core#53]
Why are we using ASP.NET 2.1 instead of the newest (3.1) ?

I tried opening Codidact using Mono, and got this error:
```
Project Codidact.Infrastructure is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Project Codidact.Infrastructure supports: netstandard2.1 (.NETStandard,Version=v2.1)
```

**Comment by asynts** [comment]
Microsoft really messed up with versioning, there is a .NET Standard, a .NET Framework and .NET Core. The most recent versions are:

  - .NET Core 3.1
  - .NET Standard 2.1
  - .NET Framework 4.7.2

Essentially, the .NET Standard is a subset of .NET Core and the infrastructure project only uses features from the standard. Thus it's setup to target `netstandard2.1` while the other projects target `netcoreapp3.1`.

Does this make sense? (No it doesn't, but that's Microsoft's fault.)
