### ISSUE TITLE
Use user secrets.

### ISSUE THREAD

**Issue by asynts** [codidact/core#56]
Currently the connection strings are stored in the `appsettings.json` files. There is also [a built in mechanism][2] to store user secrets.

Essentially, it would look like this:

~~~bash
cd src/WebUI
dotnet user-secrets init
dotnet user-secrets set ConnectionStrings:DefaultConnection "Host=localhost;Database=codidact;Username=codidact"
~~~

This could also simplify [the install instructions in #31][1].

It's not a must-have but I found that and would like to put it up for debate.

  [1]: https://github.com/codidact/core/pull/31/files#diff-bf8d8211874a23c72851c260fd543d24R59-R74
  [2]: https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=linux

**Comment by misha130** [comment]
In general having any secrets in Web.Config/appsettings.json is not recommended. 

Probably need to implement a service to retrieve secrets. 

On local development it should be dotnet secrets tool.
On Cloud its KMS/Key Vault.
On self hosted deployment server variables or I am not exactly sure.

Need to let the configuration decide which implementation to use.
