### ISSUE TITLE
Some incorrect packages are referenced.

### ISSUE THREAD

**Issue by asynts** [codidact/core#64]
The infrastructure project references a package that belongs to the ".NET Framework" framework, not to the ".NET Core" framework, namely `Microsoft.AspNet.Identity.EntityFramework`.

 https://github.com/asynts/codidact-core/blob/c1e82e109b8ef0ea67cf94f3a04471660d186878/src/Infrastructure/Infrastructure.csproj#L11

---

In another place the package `Microsoft.AspNetCore.Http.Abstractions` is included, it appears that this package was replaced by a "framework reference" whatever that is. I have not tested that but look dotnet/aspnetcore#6040 for details.

https://github.com/asynts/codidact-core/blob/c1e82e109b8ef0ea67cf94f3a04471660d186878/src/Infrastructure/Infrastructure.csproj#L12

**Comment by misha130** [comment]
The abstraction is fine since this is a .net standard project.
There is no framework reference (They basically add a bunch of libraries when you select core and not standard)

**Comment by misha130** [comment]
Actually realized that https://github.com/codidact/core/pull/61 already removes it
https://github.com/codidact/core/blob/82b4dba6f99a6ef80eecb4cdafca34ecd9fff1a3/src/Infrastructure/Infrastructure.csproj
So ignore the above PR unless #61 is rejected
